version: '3'

services:

  service-a:
    build: ./services/service-a
    container_name: service-a

  service-b:
    build: ./services/service-b
    container_name: service-b

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
