events {}

http {
    server {
        listen 80;

        location /serviceA {
            proxy_pass http://service-a:5000;
        }

        location /serviceB {
            proxy_pass http://service-b:5000;
        }
    }
}
