events {}

http {
    server {
        listen 80;

        location /serviceA {
            return 200 "Service A working";
        }

        location /serviceB {
            return 200 "Service B working";
        }
    }
}
